[package]
name = "acv"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cv = "0.6"
image = "0.24"
imageproc = "0.23"
